namespace Atc.XamlToolkit.SourceGenerators.Factories;

[SuppressMessage("MicrosoftCodeAnalysisReleaseTracking", "RS2008:Enable analyzer release tracking", Justification = "Release tracking files are not used in this project — diagnostic IDs are stable.")]
internal static class DiagnosticFactory
{
    private static readonly DiagnosticDescriptor MissingPartialKeywordDescriptor =
        new(
            id: "AtcXamlToolkit0002",
            title: "View-model class must be partial",
            messageFormat: "Class '{0}' uses [ObservableProperty], [RelayCommand], or [ComputedProperty] but is not declared 'partial'. Add the 'partial' keyword so the source generator can emit the corresponding members.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The view-model source generator requires every class that contains [ObservableProperty], [RelayCommand], or [ComputedProperty] to be partial. Without the 'partial' keyword the generator silently skips the class and the expected properties / commands never exist.");

    private static readonly DiagnosticDescriptor ObservablePropertyFieldNotPrivateDescriptor =
        new(
            id: "AtcXamlToolkit0003",
            title: "[ObservableProperty] field must be private",
            messageFormat: "Field '{0}' is decorated with [ObservableProperty] but is not declared 'private'. The source generator silently skips non-private fields. Mark the field 'private' so the generated public property pair compiles.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "[ObservableProperty] generates a public property whose backing field is the decorated field. The pattern requires the backing field to be private — otherwise the public field and the generated public property would collide.");

    private static readonly DiagnosticDescriptor ObservablePropertyFieldNameNotCamelCaseDescriptor =
        new(
            id: "AtcXamlToolkit0004",
            title: "[ObservableProperty] field must be camelCase",
            messageFormat: "Field '{0}' is decorated with [ObservableProperty] but starts with an upper-case letter. The source generator silently skips PascalCase fields. Rename the field to camelCase so the generator can derive the public property name.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The [ObservableProperty] generator infers the public property name by taking the field name and upper-casing the first letter. PascalCase fields would collide with the generated property of the same name; the generator therefore skips them.");

    private static readonly DiagnosticDescriptor NotifyPropertyChangedForNonExistentTargetDescriptor =
        new(
            id: "AtcXamlToolkit0005",
            title: "[NotifyPropertyChangedFor] references an unknown property",
            messageFormat: "[NotifyPropertyChangedFor] on field '{0}' references property '{1}' which is not declared on the class and is not generated by another [ObservableProperty] field. Either remove the reference, fix the typo, or declare the property.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The [NotifyPropertyChangedFor] attribute lists the *additional* properties whose PropertyChanged event should be raised when the source property changes. The referenced names must resolve to either user-declared properties on the class or properties that will be generated by the source generator from another [ObservableProperty] field; otherwise the generated nameof(...) call fails to compile.");

    private static readonly DiagnosticDescriptor NotifyCanExecuteChangedForNonExistentTargetDescriptor =
        new(
            id: "AtcXamlToolkit0006",
            title: "[NotifyCanExecuteChangedFor] references an unknown command",
            messageFormat: "[NotifyCanExecuteChangedFor] on field '{0}' references command '{1}' which is not declared on the class and is not generated by any [RelayCommand] method. Either remove the reference, fix the typo, or declare the command.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "The [NotifyCanExecuteChangedFor] attribute lists the relay commands whose RaiseCanExecuteChanged should fire when the source property changes. The referenced names must resolve to either user-declared command properties on the class or commands that will be generated by [RelayCommand] methods; otherwise the generated invocation fails to compile.");

    private static readonly DiagnosticDescriptor ComputedPropertyNoDependenciesDescriptor =
        new(
            id: "AtcXamlToolkit0007",
            title: "[ComputedProperty] has no detected dependencies",
            messageFormat: "Property '{0}' is decorated with [ComputedProperty] but the generator could not detect any dependencies in its getter. The attribute will have no effect — no PropertyChanged invalidation will be wired up. Reference at least one [ObservableProperty] field or another property in the getter, or remove [ComputedProperty].",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "[ComputedProperty] inspects the getter expression for identifier references that match observable properties on the same class and emits RaisePropertyChanged invalidation calls in their setters. When no such references are found, the attribute is silently inert — the generator filters the property out and the UI never refreshes when state changes.");

    private static readonly DiagnosticDescriptor ComputedPropertyCycleDescriptor =
        new(
            id: "AtcXamlToolkit0008",
            title: "[ComputedProperty] participates in a dependency cycle",
            messageFormat: "Property '{0}' participates in a [ComputedProperty] dependency cycle: {1}. Reading any property in the cycle will infinitely recurse at runtime. Break the cycle by extracting the shared computation into a non-computed helper or by making one of the properties an [ObservableProperty]-backed value.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "Two or more [ComputedProperty] getters mutually reference each other. Because the generator only wires invalidation through observable-property setters, the computed properties don't trigger update loops, but evaluating any of them at runtime will recurse infinitely until the stack overflows.");

    private static readonly DiagnosticDescriptor NotifyDataErrorInfoRequiresObservableValidatorDescriptor =
        new(
            id: "AtcXamlToolkit0009",
            title: "[NotifyDataErrorInfo] requires ObservableValidator inheritance",
            messageFormat: "Field '{0}' is decorated with [NotifyDataErrorInfo] but its containing class '{1}' does not inherit from ObservableValidator (directly or via ViewModelBase). The generated setter will fail to compile because ValidateProperty is not available. Change the base class to ObservableValidator or ViewModelBase, or remove [NotifyDataErrorInfo].",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "[NotifyDataErrorInfo] makes the generated property setter call ObservableValidator.ValidateProperty(...) inline. ValidateProperty is a protected member of ObservableValidator (and is inherited by ViewModelBase). Classes that derive from ObservableObject directly, or that use the [INotifyPropertyChanged] class-level attribute without ObservableValidator inheritance, do not have ValidateProperty in scope and will produce a confusing CS0103 inside the generated file.");

    private static readonly DiagnosticDescriptor RoutedEventOnNonWpfDescriptor =
        new(
            id: "AtcXamlToolkit0010",
            title: "[RoutedEvent] is WPF-only",
            messageFormat: "Field '{0}' is decorated with [RoutedEvent] but the project targets {1}. The source generator silently skips routed-event generation on non-WPF platforms because WinUI 3 and Avalonia have no equivalent of WPF's RoutedEvent / EventManager pattern. Replace the field with a standard CLR event (e.g. 'public event RoutedEventHandler ItemSelected;') or remove the attribute.",
            category: "Usage",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "WPF's RoutedEvent / EventManager.RegisterRoutedEvent infrastructure does not exist on WinUI 3 or Avalonia. The source generator therefore emits routed-event code only when the compilation references WPF. Without this diagnostic the [RoutedEvent] attribute would be silently inert on the wrong platform — the developer would expect an event to materialize and find nothing, with no build-time clue.");

    public static Diagnostic CreateContainsDuplicateNamesForRelayCommand()
        => Diagnostic.Create(
            new DiagnosticDescriptor(
                id: "AtcXamlToolkit0001",
                title: "Duplicate RelayCommand Name",
                messageFormat: "The RelayCommand is defined multiple times with the same name. To avoid conflicts, specify a unique commandName in the attribute.",
                category: "Hint",
                DiagnosticSeverity.Warning,
                isEnabledByDefault: true),
            Location.None);

    public static Diagnostic CreateMissingPartialKeyword(
        string className,
        Location location)
        => Diagnostic.Create(MissingPartialKeywordDescriptor, location, className);

    public static Diagnostic CreateObservablePropertyFieldNotPrivate(
        string fieldName,
        Location location)
        => Diagnostic.Create(ObservablePropertyFieldNotPrivateDescriptor, location, fieldName);

    public static Diagnostic CreateObservablePropertyFieldNameNotCamelCase(
        string fieldName,
        Location location)
        => Diagnostic.Create(ObservablePropertyFieldNameNotCamelCaseDescriptor, location, fieldName);

    public static Diagnostic CreateNotifyPropertyChangedForNonExistentTarget(
        string fieldName,
        string referencedPropertyName,
        Location location)
        => Diagnostic.Create(
            NotifyPropertyChangedForNonExistentTargetDescriptor,
            location,
            fieldName,
            referencedPropertyName);

    public static Diagnostic CreateNotifyCanExecuteChangedForNonExistentTarget(
        string fieldName,
        string referencedCommandName,
        Location location)
        => Diagnostic.Create(
            NotifyCanExecuteChangedForNonExistentTargetDescriptor,
            location,
            fieldName,
            referencedCommandName);

    public static Diagnostic CreateComputedPropertyNoDependencies(
        string propertyName,
        Location location)
        => Diagnostic.Create(
            ComputedPropertyNoDependenciesDescriptor,
            location,
            propertyName);

    public static Diagnostic CreateComputedPropertyCycle(
        string propertyName,
        string cyclePath,
        Location location)
        => Diagnostic.Create(
            ComputedPropertyCycleDescriptor,
            location,
            propertyName,
            cyclePath);

    public static Diagnostic CreateNotifyDataErrorInfoRequiresObservableValidator(
        string fieldName,
        string className,
        Location location)
        => Diagnostic.Create(
            NotifyDataErrorInfoRequiresObservableValidatorDescriptor,
            location,
            fieldName,
            className);

    public static Diagnostic CreateRoutedEventOnNonWpf(
        string fieldName,
        string platformName,
        Location location)
        => Diagnostic.Create(
            RoutedEventOnNonWpfDescriptor,
            location,
            fieldName,
            platformName);
}