namespace Atc.XamlToolkit.SourceGenerators.Generators;

/// <summary>
/// Source generator for generating view model properties and commands.
/// </summary>
[Generator]
public sealed class ViewModelGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the source generator.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ////#if DEBUG
        ////        if (!System.Diagnostics.Debugger.IsAttached)
        ////        {
        ////            System.Diagnostics.Debugger.Launch();
        ////        }
        ////#endif

        var viewModelsToGenerate = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (syntaxNode, _) => ViewModelGeneratorHelper.IsSyntaxTarget(syntaxNode),
                transform: static (context, _) => ViewModelGeneratorHelper.GetSemanticTarget(context))
            .Where(static target => target is not null)
            .WithTrackingName("ViewModelGenerator.SemanticTarget")
            .Collect()
            .Select(static (viewModels, _) => viewModels
                .GroupBy(vm => vm!.GeneratedFileName, StringComparer.Ordinal)
                .Select(static group => group.First())
                .ToImmutableArray())
            .WithTrackingName("ViewModelGenerator.Deduplicated");

        context.RegisterSourceOutput(
            viewModelsToGenerate,
            static (spc, sources) =>
            {
                foreach (var source in sources)
                {
                    Execute(spc, source);
                }
            });

        // Classes annotated with [INotifyPropertyChanged] — emit the INPC scaffolding
        // (event + RaisePropertyChanged + OnPropertyChanged + Set<T>) so the class can act
        // as its own INPC source without inheriting from ObservableObject. Compatible with
        // [ObservableProperty] on the same class.
        var inpcTargets = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (syntaxNode, _) => ViewModelGeneratorHelper.IsINotifyPropertyChangedTarget(syntaxNode),
                transform: static (context, _) => ViewModelGeneratorHelper.GetINotifyPropertyChangedTarget(context))
            .Where(static target => target is not null)
            .WithTrackingName("ViewModelGenerator.INotifyPropertyChangedTarget");

        context.RegisterSourceOutput(
            inpcTargets,
            static (spc, target) =>
            {
                if (target is not null)
                {
                    ExecuteINotifyPropertyChanged(spc, target);
                }
            });

        ViewModelDiagnosticHelper.RegisterAll(context);
    }

    /// <summary>
    /// Executes the source generation process.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="viewModelToGenerate">The ViewModel to generate.</param>
    private static void Execute(
        SourceProductionContext context,
        ViewModelToGenerate? viewModelToGenerate)
    {
        if (viewModelToGenerate is null)
        {
            return;
        }

        var viewModelBuilder = new ViewModelBuilder
        {
            XamlPlatform = viewModelToGenerate.XamlPlatform,
        };

        viewModelBuilder.GenerateStart(viewModelToGenerate);

        if (viewModelToGenerate.ContainsRelayCommandNameDuplicates)
        {
            context.ReportDiagnostic(DiagnosticFactory.CreateContainsDuplicateNamesForRelayCommand());
        }
        else
        {
            viewModelBuilder.GenerateRelayCommands(viewModelBuilder, viewModelToGenerate.RelayCommandsToGenerate);
        }

        viewModelBuilder.GenerateProperties(viewModelToGenerate.PropertiesToGenerate);

        viewModelBuilder.GenerateRelayCommandMethods(viewModelBuilder, viewModelToGenerate.RelayCommandsToGenerate);

        viewModelBuilder.GenerateEnd();

        var sourceText = viewModelBuilder.ToSourceText();

        context.AddSource(
            viewModelToGenerate.GeneratedFileName,
            sourceText);
    }

    private static void ExecuteINotifyPropertyChanged(
        SourceProductionContext context,
        INotifyPropertyChangedTarget? target)
    {
        if (target is null)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.NamespaceName};");
        sb.AppendLine();
        sb.AppendLine($"{target.AccessModifier} partial class {target.ClassName} : INotifyPropertyChanged");
        sb.AppendLine("{");
        sb.AppendLine("    public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();
        sb.AppendLine("    protected void RaisePropertyChanged([CallerMemberName] string? propertyName = null)");
        sb.AppendLine("        => PropertyChanged?.Invoke(this, Atc.XamlToolkit.Mvvm.PropertyChangedEventArgsCache.Get(propertyName));");
        sb.AppendLine();
        sb.AppendLine("    protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)");
        sb.AppendLine("        => RaisePropertyChanged(propertyName);");
        sb.AppendLine();
        sb.AppendLine("    protected bool Set<T>(ref T field, T newValue, [CallerMemberName] string? propertyName = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (EqualityComparer<T>.Default.Equals(field, newValue))");
        sb.AppendLine("        {");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        field = newValue;");
        sb.AppendLine("        RaisePropertyChanged(propertyName);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append("#nullable disable");

        context.AddSource(
            $"{target.ClassName}.INotifyPropertyChanged.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}