// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class FrameworkElementGeneratorTests
{
    [Fact]
    public void DependencyProperty_Field_GenerateDocumentation_True_EmitsDefaultSummary()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(GenerateDocumentation = true)]
                private bool isRunning;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty IsRunningProperty = DependencyProperty.Register(
                    nameof(IsRunning),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets or sets the IsRunning.
                /// </summary>
                public bool IsRunning
                {
                    get => (bool)GetValue(IsRunningProperty);
                    set => SetValue(IsRunningProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_GenerateDocumentation_False_NoSummary()
    {
        // Pinning the byte-identical-default contract for [DependencyProperty].
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(GenerateDocumentation = false)]
                private bool isRunning;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty IsRunningProperty = DependencyProperty.Register(
                    nameof(IsRunning),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                public bool IsRunning
                {
                    get => (bool)GetValue(IsRunningProperty);
                    set => SetValue(IsRunningProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Class_GenerateDocumentation_True_EmitsDefaultSummary()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            [DependencyProperty<bool>("IsRunning", GenerateDocumentation = true)]
            public partial class MyControl : UserControl
            {
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty IsRunningProperty = DependencyProperty.Register(
                    nameof(IsRunning),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets or sets the IsRunning.
                /// </summary>
                public bool IsRunning
                {
                    get => (bool)GetValue(IsRunningProperty);
                    set => SetValue(IsRunningProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_AssemblyAttribute_FlipsDefault_ToOn()
    {
        // [assembly: GenerateDocumentationDefault] should also affect [DependencyProperty].
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty]
                private bool isRunning;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty IsRunningProperty = DependencyProperty.Register(
                    nameof(IsRunning),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets or sets the IsRunning.
                /// </summary>
                public bool IsRunning
                {
                    get => (bool)GetValue(IsRunningProperty);
                    set => SetValue(IsRunningProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}