// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class FrameworkElementGeneratorTests
{
    [Fact]
    public void DependencyProperty_Field_WithDocumentationComments_CopiesDocs()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                /// <summary>
                /// Gets or sets a value indicating whether the pane is open.
                /// </summary>
                /// <remarks>
                /// The pane is closed by default.
                /// </remarks>
                [DependencyProperty]
                private bool isOpen;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                /// <summary>
                /// Identifies the <see cref="IsOpen"/> dependency property.
                /// </summary>
                public static readonly DependencyProperty IsOpenProperty = DependencyProperty.Register(
                    nameof(IsOpen),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets or sets a value indicating whether the pane is open.
                /// </summary>
                /// <remarks>
                /// The pane is closed by default.
                /// </remarks>
                public bool IsOpen
                {
                    get => (bool)GetValue(IsOpenProperty);
                    set => SetValue(IsOpenProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_WithDocumentationComments_AndGenerateDocumentation_DocsWin()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                /// <summary>
                /// Gets or sets a value indicating whether the pane is open.
                /// </summary>
                [DependencyProperty(GenerateDocumentation = true)]
                private bool isOpen;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                /// <summary>
                /// Identifies the <see cref="IsOpen"/> dependency property.
                /// </summary>
                public static readonly DependencyProperty IsOpenProperty = DependencyProperty.Register(
                    nameof(IsOpen),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets or sets a value indicating whether the pane is open.
                /// </summary>
                public bool IsOpen
                {
                    get => (bool)GetValue(IsOpenProperty);
                    set => SetValue(IsOpenProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_StaticOwner_WithDocumentationComments_CopiesDocsToAccessors()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public static partial class CheckBoxHelper
            {
                /// <summary>
                /// The check mark is drawn on the right side.
                /// </summary>
                [DependencyProperty]
                private static bool isRightAligned;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class CheckBoxHelper
            {
                /// <summary>
                /// Identifies the IsRightAligned attached property.
                /// </summary>
                public static readonly DependencyProperty IsRightAlignedProperty = DependencyProperty.Register(
                    "IsRightAligned",
                    typeof(bool),
                    typeof(CheckBoxHelper),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// The check mark is drawn on the right side.
                /// </summary>
                public static bool GetIsRightAligned(DependencyObject element)
                    => (bool)element.GetValue(IsRightAlignedProperty);

                /// <summary>
                /// The check mark is drawn on the right side.
                /// </summary>
                public static void SetIsRightAligned(DependencyObject element, bool value)
                    => element?.SetValue(IsRightAlignedProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AttachedProperty_Field_WithDocumentationComments_CopiesDocsToAccessors()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public static partial class DragBehavior
            {
                /// <summary>
                /// Allows the element to be dragged.
                /// </summary>
                [AttachedProperty]
                private static bool isDraggable;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                /// <summary>
                /// Identifies the IsDraggable attached property.
                /// </summary>
                public static readonly DependencyProperty IsDraggableProperty = DependencyProperty.RegisterAttached(
                    "IsDraggable",
                    typeof(bool),
                    typeof(DragBehavior),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Allows the element to be dragged.
                /// </summary>
                public static bool GetIsDraggable(DependencyObject element)
                    => (bool)element.GetValue(IsDraggableProperty);

                /// <summary>
                /// Allows the element to be dragged.
                /// </summary>
                public static void SetIsDraggable(DependencyObject element, bool value)
                    => element?.SetValue(IsDraggableProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Class_GenerateDocumentation_False_NoDocs()
    {
        // The class form has no field to copy docs from.
        const string inputCode =
            """
            namespace TestNamespace;

            /// <summary>
            /// My control.
            /// </summary>
            [DependencyProperty<bool>("IsRunning")]
            public partial class MyControl : UserControl
            {
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty IsRunningProperty = DependencyProperty.Register(
                    nameof(IsRunning),
                    typeof(bool),
                    typeof(MyControl),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                public bool IsRunning
                {
                    get => (bool)GetValue(IsRunningProperty);
                    set => SetValue(IsRunningProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void RoutedEvent_WithDocumentationComments_CopiesDocs()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class CustomButton : Button
            {
                /// <summary>
                /// Occurs when the button is tapped.
                /// </summary>
                [RoutedEvent(RoutingStrategy.Bubble)]
                private static readonly RoutedEvent tap;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class CustomButton
            {
                /// <summary>
                /// Identifies the <see cref="Tap"/> routed event.
                /// </summary>
                public static readonly RoutedEvent TapEvent = EventManager.RegisterRoutedEvent(
                    name: nameof(Tap),
                    routingStrategy: RoutingStrategy.Bubble,
                    handlerType: typeof(RoutedEventHandler),
                    ownerType: typeof(CustomButton));

                /// <summary>
                /// Occurs when the button is tapped.
                /// </summary>
                public event RoutedEventHandler Tap
                {
                    add => AddHandler(TapEvent, value);
                    remove => RemoveHandler(TapEvent, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void RelayCommand_WithDocumentationComments_CopiesDocsWithoutMethodOnlyElements()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestControl : UserControl
            {
                /// <summary>
                /// Opens the <paramref name="item"/>.
                /// </summary>
                /// <param name="item">
                /// The item to open.
                /// </param>
                /// <remarks>Does nothing when the item is empty.</remarks>
                [RelayCommand]
                public void Open(string item)
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestControl
            {
                private IRelayCommand<string>? openCommand;

                /// <summary>
                /// Opens the <c>item</c>.
                /// </summary>
                /// <remarks>Does nothing when the item is empty.</remarks>
                public IRelayCommand<string> OpenCommand => openCommand ??= new RelayCommand<string>(Open);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void StyledProperty_Field_OnAvalonia_WithDocumentationComments_CopiesDocs()
    {
        const string inputCode =
            """
            namespace Avalonia
            {
                public class AvaloniaProperty { }
            }

            namespace TestNamespace
            {
                public partial class MyControl : UserControl
                {
                    /// <summary>
                    /// Gets or sets a value indicating whether the pane is open.
                    /// </summary>
                    [StyledProperty]
                    private bool isOpen;
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                /// <summary>
                /// Identifies the <see cref="IsOpen"/> styled property.
                /// </summary>
                public static readonly StyledProperty<bool> IsOpenProperty = Avalonia.AvaloniaProperty.Register<MyControl, bool>(
                    nameof(IsOpen),
                    defaultValue: false);

                /// <summary>
                /// Gets or sets a value indicating whether the pane is open.
                /// </summary>
                public bool IsOpen
                {
                    get => (bool)GetValue(IsOpenProperty)!;
                    set => SetValue(IsOpenProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}