// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class FrameworkElementGeneratorTests
{
    [Fact]
    public void AttachedProperty_Field_GenerateDocumentation_True_EmitsDefaultSummaryOnAccessors()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public static partial class DragBehavior
            {
                [AttachedProperty(GenerateDocumentation = true)]
                private static bool isDraggable;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                public static readonly DependencyProperty IsDraggableProperty = DependencyProperty.RegisterAttached(
                    "IsDraggable",
                    typeof(bool),
                    typeof(DragBehavior),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets the IsDraggable attached property value.
                /// </summary>
                public static bool GetIsDraggable(DependencyObject element)
                    => (bool)element.GetValue(IsDraggableProperty);

                /// <summary>
                /// Sets the IsDraggable attached property value.
                /// </summary>
                public static void SetIsDraggable(DependencyObject element, bool value)
                    => element?.SetValue(IsDraggableProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AttachedProperty_Field_GenerateDocumentation_False_NoSummary()
    {
        // Pinning the byte-identical-default contract for [AttachedProperty].
        const string inputCode =
            """
            namespace TestNamespace;

            public static partial class DragBehavior
            {
                [AttachedProperty(GenerateDocumentation = false)]
                private static bool isDraggable;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                public static readonly DependencyProperty IsDraggableProperty = DependencyProperty.RegisterAttached(
                    "IsDraggable",
                    typeof(bool),
                    typeof(DragBehavior),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                public static bool GetIsDraggable(DependencyObject element)
                    => (bool)element.GetValue(IsDraggableProperty);

                public static void SetIsDraggable(DependencyObject element, bool value)
                    => element?.SetValue(IsDraggableProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AttachedProperty_Field_AssemblyAttribute_FlipsDefault_ToOn()
    {
        // [assembly: GenerateDocumentationDefault] should also affect [AttachedProperty].
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                [AttachedProperty]
                private static bool isDraggable;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                public static readonly DependencyProperty IsDraggableProperty = DependencyProperty.RegisterAttached(
                    "IsDraggable",
                    typeof(bool),
                    typeof(DragBehavior),
                    new PropertyMetadata(defaultValue: Atc.XamlToolkit.BooleanBoxes.FalseBox));

                /// <summary>
                /// Gets the IsDraggable attached property value.
                /// </summary>
                public static bool GetIsDraggable(DependencyObject element)
                    => (bool)element.GetValue(IsDraggableProperty);

                /// <summary>
                /// Sets the IsDraggable attached property value.
                /// </summary>
                public static void SetIsDraggable(DependencyObject element, bool value)
                    => element?.SetValue(IsDraggableProperty, Atc.XamlToolkit.BooleanBoxes.Box(value));
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}