namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

/// <summary>
/// Combinations where WPF needs the full FrameworkPropertyMetadata constructor,
/// so missing flags/callbacks must be written with neutral values.
/// </summary>
[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class FrameworkElementGeneratorTests
{
    [Fact]
    public void DependencyProperty_Field_Int_Flags_IsAnimationProhibited()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(Flags = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault | FrameworkPropertyMetadataOptions.Journal, IsAnimationProhibited = true)]
                private int valueWidth;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty ValueWidthProperty = DependencyProperty.Register(
                    nameof(ValueWidth),
                    typeof(int),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0,
                        flags: FrameworkPropertyMetadataOptions.BindsTwoWayByDefault | FrameworkPropertyMetadataOptions.Journal,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true));

                public int ValueWidth
                {
                    get => (int)GetValue(ValueWidthProperty);
                    set => SetValue(ValueWidthProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_Decimal_DefaultValue_Flags_IsAnimationProhibited_DefaultUpdateSourceTrigger()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(DefaultValue = 0, Flags = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault | FrameworkPropertyMetadataOptions.Journal, IsAnimationProhibited = true, DefaultUpdateSourceTrigger = UpdateSourceTrigger.LostFocus)]
                private decimal valueX;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using System.Windows.Data;

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty ValueXProperty = DependencyProperty.Register(
                    nameof(ValueX),
                    typeof(decimal),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0m,
                        flags: FrameworkPropertyMetadataOptions.BindsTwoWayByDefault | FrameworkPropertyMetadataOptions.Journal,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true,
                        defaultUpdateSourceTrigger: UpdateSourceTrigger.LostFocus));

                public decimal ValueX
                {
                    get => (decimal)GetValue(ValueXProperty);
                    set => SetValue(ValueXProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_String_Flags_DefaultUpdateSourceTrigger()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(Flags = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, DefaultUpdateSourceTrigger = UpdateSourceTrigger.LostFocus)]
                private string text;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using System.Windows.Data;

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty TextProperty = DependencyProperty.Register(
                    nameof(Text),
                    typeof(string),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: null,
                        flags: FrameworkPropertyMetadataOptions.BindsTwoWayByDefault,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: false,
                        defaultUpdateSourceTrigger: UpdateSourceTrigger.LostFocus));

                public string Text
                {
                    get => (string)GetValue(TextProperty);
                    set => SetValue(TextProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_Double_Flags_CoerceValueCallback()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(Flags = FrameworkPropertyMetadataOptions.AffectsMeasure, CoerceValueCallback = nameof(CoerceSize))]
                private double size;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty SizeProperty = DependencyProperty.Register(
                    nameof(Size),
                    typeof(double),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0d,
                        flags: FrameworkPropertyMetadataOptions.AffectsMeasure,
                        propertyChangedCallback: null,
                        coerceValueCallback: CoerceSize));

                public double Size
                {
                    get => (double)GetValue(SizeProperty);
                    set => SetValue(SizeProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_String_PropertyChangedCallback_DefaultUpdateSourceTrigger()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(PropertyChangedCallback = nameof(OnTextChanged), DefaultUpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged)]
                private string text;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using System.Windows.Data;

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty TextProperty = DependencyProperty.Register(
                    nameof(Text),
                    typeof(string),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: null,
                        flags: FrameworkPropertyMetadataOptions.None,
                        propertyChangedCallback: OnTextChanged,
                        coerceValueCallback: null,
                        isAnimationProhibited: false,
                        defaultUpdateSourceTrigger: UpdateSourceTrigger.PropertyChanged));

                public string Text
                {
                    get => (string)GetValue(TextProperty);
                    set => SetValue(TextProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_Int_IsAnimationProhibited_DefaultUpdateSourceTrigger()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(IsAnimationProhibited = true, DefaultUpdateSourceTrigger = UpdateSourceTrigger.LostFocus)]
                private int count;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using System.Windows.Data;

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty CountProperty = DependencyProperty.Register(
                    nameof(Count),
                    typeof(int),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0,
                        flags: FrameworkPropertyMetadataOptions.None,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true,
                        defaultUpdateSourceTrigger: UpdateSourceTrigger.LostFocus));

                public int Count
                {
                    get => (int)GetValue(CountProperty);
                    set => SetValue(CountProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Field_Double_IsAnimationProhibited()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class MyControl : UserControl
            {
                [DependencyProperty(IsAnimationProhibited = true)]
                private double opacityLevel;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty OpacityLevelProperty = DependencyProperty.Register(
                    nameof(OpacityLevel),
                    typeof(double),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0d,
                        flags: FrameworkPropertyMetadataOptions.None,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true));

                public double OpacityLevel
                {
                    get => (double)GetValue(OpacityLevelProperty);
                    set => SetValue(OpacityLevelProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DependencyProperty_Class_Int_IsAnimationProhibited_DefaultUpdateSourceTrigger()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            [DependencyProperty<int>("Count", IsAnimationProhibited = true, DefaultUpdateSourceTrigger = UpdateSourceTrigger.LostFocus)]
            public partial class MyControl : UserControl
            {
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using System.Windows.Data;

            namespace TestNamespace;

            public partial class MyControl
            {
                public static readonly DependencyProperty CountProperty = DependencyProperty.Register(
                    nameof(Count),
                    typeof(int),
                    typeof(MyControl),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0,
                        flags: FrameworkPropertyMetadataOptions.None,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true,
                        defaultUpdateSourceTrigger: UpdateSourceTrigger.LostFocus));

                public int Count
                {
                    get => (int)GetValue(CountProperty);
                    set => SetValue(CountProperty, value);
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AttachedProperty_Class_Int_Flags_IsAnimationProhibited()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            [AttachedProperty<int>("Count", Flags = FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, IsAnimationProhibited = true)]
            public static partial class DragBehavior
            {
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public static partial class DragBehavior
            {
                public static readonly DependencyProperty CountProperty = DependencyProperty.RegisterAttached(
                    "Count",
                    typeof(int),
                    typeof(DragBehavior),
                    new FrameworkPropertyMetadata(
                        defaultValue: 0,
                        flags: FrameworkPropertyMetadataOptions.BindsTwoWayByDefault,
                        propertyChangedCallback: null,
                        coerceValueCallback: null,
                        isAnimationProhibited: true));

                public static int GetCount(DependencyObject element)
                    => (int)element.GetValue(CountProperty);

                public static void SetCount(DependencyObject element, int value)
                    => element?.SetValue(CountProperty, value);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<FrameworkElementGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}