namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0051:Method is too long", Justification = "OK.")]
public sealed partial class ViewModelGeneratorTests : GeneratorTestBase
{
    [Fact]
    public void ClassAccessor_Invalid()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultIsEmpty(generatorResult);
    }

    [Fact]
    public void MissingPartial_OnObservableProperty_EmitsDiagnostic()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        var (_, diagnostics) = RunGenerator<ViewModelGenerator>(inputCode);

        Assert.Contains(diagnostics, d => d.Id == "AtcXamlToolkit0002");
    }

    [Fact]
    public void MissingPartial_OnRelayCommand_EmitsDiagnostic()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public class TestViewModel : ViewModelBase
            {
                [RelayCommand]
                private void Save()
                {
                }
            }
            """;

        var (_, diagnostics) = RunGenerator<ViewModelGenerator>(inputCode);

        Assert.Contains(diagnostics, d => d.Id == "AtcXamlToolkit0002");
    }

    [Fact]
    public void PartialClass_WithObservableProperty_DoesNotEmitMissingPartialDiagnostic()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        var (_, diagnostics) = RunGenerator<ViewModelGenerator>(inputCode);

        Assert.DoesNotContain(diagnostics, d => d.Id == "AtcXamlToolkit0002");
    }

    [Fact]
    public void NonPartial_WithoutGeneratorAttributes_DoesNotEmitMissingPartialDiagnostic()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public class PlainOldClass
            {
                public string Name { get; set; } = string.Empty;
            }
            """;

        var (_, diagnostics) = RunGenerator<ViewModelGenerator>(inputCode);

        Assert.DoesNotContain(diagnostics, d => d.Id == "AtcXamlToolkit0002");
    }

    [Fact]
    public void MultiFiles4_ObservableProperty_Name_And_RelayCommand_NoParameter()
    {
        const string inputCode_MyViewModelBase =
            """
            namespace TestNamespace;

            public class MyViewModelBase : ViewModelBase
            {
            }
            """;

        const string inputCode_TestViewModel_Base =
            """
            namespace TestNamespace;

            public partial class TestViewModel : MyViewModelBase
            {
            }
            """;

        const string inputCode_TestViewModel_ObservableProperties =
            """
            namespace TestNamespace;

            public partial class TestViewModel
            {
                [ObservableProperty]
                private string name;
            }
            """;

        const string inputCode_TestViewModel_RelayCommands =
            """
            namespace TestNamespace;

            public partial class TestViewModel
            {
                [RelayCommand]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);

                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }

                        name = value;
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(
            inputCode_MyViewModelBase,
            inputCode_TestViewModel_Base,
            inputCode_TestViewModel_ObservableProperties,
            inputCode_TestViewModel_RelayCommands);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void PartialClass_SplitAcrossFiles_AggregatesObservablePropertiesFromAllParts()
    {
        const string inputCode_PartA =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string firstName;
            }
            """;

        const string inputCode_PartB =
            """
            namespace TestNamespace;

            public partial class TestViewModel
            {
                [ObservableProperty]
                private string lastName;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }

                public string LastName
                {
                    get => lastName;
                    set
                    {
                        if (lastName == value)
                        {
                            return;
                        }

                        lastName = value;
                        RaisePropertyChanged(nameof(LastName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(
            inputCode_PartA,
            inputCode_PartB);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}