namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class ViewModelGeneratorTests
{
    [Fact]
    public void ObservableProperty_GeneratePartialHooks_True_EmitsPartialDeclarationsAndCalls()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(GeneratePartialHooks = true)]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                partial void OnNameChanging(string value);

                partial void OnNameChanged(string value);

                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }

                        OnNameChanging(value);
                        name = value;
                        OnNameChanged(value);
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_GeneratePartialHooks_False_DoesNotEmitPartialDeclarationsOrCalls()
    {
        // Negative test: verify the existing default behaviour is preserved
        // when the new opt-in flag is absent. The output must match the bare
        // ObservableProperty_Name test (no partial hooks anywhere).
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        var generated = generatorResult.GeneratorResult.GeneratedSources[0]
            .SourceText
            .ToString();

        generated.Should().NotContain("partial void OnNameChanging");
        generated.Should().NotContain("partial void OnNameChanged");
        generated.Should().NotContain("OnNameChanging(value)");
        generated.Should().NotContain("OnNameChanged(value)");
    }

    [Fact]
    public void ObservableProperty_GeneratePartialHooks_True_ComposesWithBeforeAfterChangedCallbacks()
    {
        // When both partial hooks AND string-named callbacks are configured,
        // partial-method calls fire first, then string-named callbacks. This
        // pins ordering so consumers can rely on it.
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(
                    GeneratePartialHooks = true,
                    BeforeChangedCallback = nameof(LogIncoming),
                    AfterChangedCallback = nameof(LogOutgoing))]
                private string name;

                private void LogIncoming() { }
                private void LogOutgoing() { }
            }
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        var generated = generatorResult.GeneratorResult.GeneratedSources[0]
            .SourceText
            .ToString();

        generated.Should().Contain("partial void OnNameChanging(string value);");
        generated.Should().Contain("partial void OnNameChanged(string value);");

        // Order check: OnNameChanging must precede LogIncoming in the setter,
        // OnNameChanged must precede LogOutgoing.
        var changingIdx = generated.IndexOf("OnNameChanging(value);", StringComparison.Ordinal);
        var logIncomingIdx = generated.IndexOf("LogIncoming();", StringComparison.Ordinal);
        var changedIdx = generated.IndexOf("OnNameChanged(value);", StringComparison.Ordinal);
        var logOutgoingIdx = generated.IndexOf("LogOutgoing();", StringComparison.Ordinal);

        changingIdx.Should().BeGreaterThan(0);
        logIncomingIdx.Should().BeGreaterThan(changingIdx, "partial-hook calls must fire before the string-named BeforeChangedCallback");
        changedIdx.Should().BeGreaterThan(0);
        logOutgoingIdx.Should().BeGreaterThan(changedIdx, "partial-hook calls must fire before the string-named AfterChangedCallback");
    }
}