// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

public class ViewModelGeneratorTests_ObservableProperty_GenerateDocumentation : GeneratorTestBase
{
    [Fact]
    public void GenerateDocumentation_True_NoFieldDocs_EmitsDefaultSummary()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(GenerateDocumentation = true)]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                /// <summary>
                /// Gets or sets the FirstName.
                /// </summary>
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_False_NoFieldDocs_EmitsNoSummary()
    {
        // Pinning the default-off behaviour: existing snapshots stay byte-identical.
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(GenerateDocumentation = false)]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_True_WithFieldDocs_PreservesFieldDocs()
    {
        // When the field already carries XML doc comments, those win — the
        // GenerateDocumentation flag is a *fallback* for fields with no docs,
        // not a replacement for hand-written docs.
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                /// <summary>
                /// Gets or sets the customer's first name.
                /// </summary>
                [ObservableProperty(GenerateDocumentation = true)]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                /// <summary>
                /// Gets or sets the customer's first name.
                /// </summary>
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_True_WithCustomPropertyName_UsesPropertyName()
    {
        // The default summary uses the *property* name, not the backing field name.
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty("CustomName", GenerateDocumentation = true)]
                private string fieldName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                /// <summary>
                /// Gets or sets the CustomName.
                /// </summary>
                public string CustomName
                {
                    get => fieldName;
                    set
                    {
                        if (fieldName == value)
                        {
                            return;
                        }

                        fieldName = value;
                        RaisePropertyChanged(nameof(CustomName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}