// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

public class ViewModelGeneratorTests_ObservableProperty_GenerateDocumentationDefault : GeneratorTestBase
{
    [Fact]
    public void AssemblyAttribute_NoPerFieldFlag_EmitsDefaultSummary()
    {
        // [assembly: GenerateDocumentationDefault] should flip the per-property
        // default — plain [ObservableProperty] now emits the default summary
        // without the user setting GenerateDocumentation = true on every field.
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                /// <summary>
                /// Gets or sets the FirstName.
                /// </summary>
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AssemblyAttribute_PerFieldFalseOverride_EmitsNoSummary()
    {
        // Per-property GenerateDocumentation = false overrides the assembly
        // default — explicit opt-out wins.
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(GenerateDocumentation = false)]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void NoAssemblyAttribute_NoPerFieldFlag_EmitsNoSummary()
    {
        // Pinning the regression contract: without the assembly attribute,
        // plain [ObservableProperty] still produces no documentation. This is
        // what keeps the 412 pre-existing snapshot tests byte-identical.
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string firstName = string.Empty;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}