// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

public class ViewModelGeneratorTests_RelayCommand_GenerateDocumentation : GeneratorTestBase
{
    [Fact]
    public void GenerateDocumentation_True_EmitsDefaultSummaryOnCommandProperty()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand(GenerateDocumentation = true)]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                /// <summary>
                /// Gets the SaveCommand.
                /// </summary>
                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_False_NoDefaultSummary()
    {
        // Pinning the byte-identical-default contract for [RelayCommand].
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand(GenerateDocumentation = false)]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AssemblyAttribute_FlipsCommandDefault_ToOn()
    {
        // [assembly: GenerateDocumentationDefault] should also affect [RelayCommand].
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                /// <summary>
                /// Gets the SaveCommand.
                /// </summary>
                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}