// ReSharper disable StringLiteralTypo
namespace Atc.XamlToolkit.SourceGenerators.Tests.Generators;

public class ViewModelGeneratorTests_RelayCommand_GenerateDocumentation : GeneratorTestBase
{
    [Fact]
    public void GenerateDocumentation_True_EmitsDefaultSummaryOnCommandProperty()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand(GenerateDocumentation = true)]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                /// <summary>
                /// Gets the SaveCommand.
                /// </summary>
                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_False_NoDefaultSummary()
    {
        // Pinning the byte-identical-default contract for [RelayCommand].
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand(GenerateDocumentation = false)]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void AssemblyAttribute_FlipsCommandDefault_ToOn()
    {
        // [assembly: GenerateDocumentationDefault] should also affect [RelayCommand].
        const string inputCode =
            """
            using Atc.XamlToolkit.Mvvm;

            [assembly: GenerateDocumentationDefault]

            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                /// <summary>
                /// Gets the SaveCommand.
                /// </summary>
                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DocumentationComments_OnMethod_AreCopiedAndWinOverGenerateDocumentation()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                /// <summary>
                /// Saves the current document.
                /// </summary>
                /// <remarks>
                /// The document is saved to its original location.
                /// </remarks>
                [RelayCommand(GenerateDocumentation = true)]
                private void Save()
                {
                }
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommand? saveCommand;

                /// <summary>
                /// Saves the current document.
                /// </summary>
                /// <remarks>
                /// The document is saved to its original location.
                /// </remarks>
                public IRelayCommand SaveCommand => saveCommand ??= new RelayCommand(Save);
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void DocumentationComments_OnAsyncMethod_StripParamAndReturns()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                /// <summary>
                /// Loads the customer.
                /// </summary>
                /// <param name="customerId">The customer id.</param>
                /// <returns>
                /// A task that completes when the customer is loaded.
                /// </returns>
                [RelayCommand]
                private Task Load(int customerId)
                    => Task.CompletedTask;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommandAsync<int>? loadCommand;

                /// <summary>
                /// Loads the customer.
                /// </summary>
                public IRelayCommandAsync<int> LoadCommand => loadCommand ??= new RelayCommandAsync<int>(Load);

                /// <summary>
                /// Disposes the async commands and releases their cancellation resources.
                /// </summary>
                public void DisposeCommands()
                {
                    LoadCommand.Dispose();
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void GenerateDocumentation_True_OnAsyncCommand_EmitsSummaryOnDisposeCommands()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [RelayCommand(GenerateDocumentation = true)]
                private Task Load()
                    => Task.CompletedTask;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            using Atc.XamlToolkit.Command;

            namespace TestNamespace;

            public partial class TestViewModel
            {
                private IRelayCommandAsync? loadCommand;

                /// <summary>
                /// Gets the LoadCommand.
                /// </summary>
                public IRelayCommandAsync LoadCommand => loadCommand ??= new RelayCommandAsync(Load);

                /// <summary>
                /// Disposes the async commands and releases their cancellation resources.
                /// </summary>
                public void DisposeCommands()
                {
                    LoadCommand.Dispose();
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}